spring:
  datasource:
    url: jdbc:postgresql://159.89.190.142:5432/project
    driver-class-name: org.postgresql.Driver
    username: project
    password: project

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
